### ISSUE TITLE
[Feature Request] Indicate Origin Encryption Status

### ISSUE THREAD

**Issue by tonyztan** [cloudflare/claire#17]
About a year ago, Nick Sullivan (@grittygrease) from CloudFlare [promised that Claire would soon "be updated to indicate the back-end encryption chosen by the site"](https://blog.cloudflare.com/introducing-strict-ssl-protecting-against-a-man-in-the-middle-attack-on-origin-traffic/#comment-1245938178), in response to a user questioning CloudFlare SSL's (lack of) security when websites do not use the "Strict" SSL setting. As far as I can tell, this has not yet been implemented.

It is very important for users to be able to tell whether their connection to a website is fully encrypted, or if the data that they send travel through a significant portion of the public Internet unencrypted after SSL is terminated at CloudFlare's servers. This is especially important if they are completing a financial transaction or otherwise transmitting highly sensitive information.

Currently, there are three possible ways SSL could be enabled for a CloudFlare-powered website: "Flexible", "Full", and "Strict". Of these options, only "Strict" provides the same level of security as a traditional SSL connection directly from the user to the website server. "Flexible" provides no encryption between CloudFlare's data center and the website server (over the public Internet), and in "Full" mode CloudFlare does not verify the identity of the server, allowing for a completely undetectable Man-in-the-Middle attack between CloudFlare and the web server (also over the public Internet).

**Comment by Profforgr** [comment]
It may make life for NSA easier as they can understand when they can MITM the data. I doubt that such "for users" feature is reasonable for whole CloudFlare-powered website security.

**Comment by TonyZTan** [comment]
@Profforgr That's a good point, but maybe the NSA already monitors Internet backbone traffic around the world and therefore already knows which websites can be MitM attacked?

Moreover, this feature may also help to encourage websites to switch to strict encryption. By making this information available, we can tell which websites are not using "true" HTTPS and then request them to fix it if the website should be more secure. (i.e. if it is related to finance, health, etc.)

**Comment by Profforgr** [comment]
> That's a good point, but maybe the NSA already monitors Internet backbone traffic around the world and therefore already knows which websites can be MitM attacked?

They probably do. But if they don't, more information will help them.

> Moreover, this feature may also help to encourage websites to switch to strict encryption. By making this information available, we can tell which websites are not using "true" HTTPS and then request them to fix it if the website should be more secure. (i.e. if it is related to finance, health, etc.)

If particular website is using Flexible/Full SSL it's probably not to decrease security, but because there are no choice or it costs them money (e.g. on some clouds or webhosting). I doubt that you should call website "bad" in this case. From your link "We are automatically upgrading customers from Full SSL to Full SSL (Strict) if we determine that their origin server has a valid certificate installed." it means, that basically all websites who support that, already upgraded to Strict.

**Comment by TonyZTan** [comment]
I understand that there are many cases where Flexible/Full SSL (non-strict) is both useful and necessary.  (Such as if you are using GitHub pages with a custom domain.) They are not "bad" websites, as not all websites require the same level of security. Almost any encryption is better than no encryption.

However, perhaps more information would let us see if there are any sites that *should* be using Full SSL (Strict) but for some reasons are not. Maybe a webmaster has the ability to yet neglects to install a proper SSL certificate on the server because he sees no point in doing so? Users have no way to tell anyways. The proposed feature would provide the information, and aid (conscious) users in deciding whether it is safe to submit their credit card and billing information through a certain website.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
